ROOT = ../..

FOMEGA = $(ROOT)/_build/default/src/main.exe

FILES = $(wildcard *.fw)

FFILES = $(filter fail_%, $(FILES))

XFILES = $(filter ext_%, $(FILES))

TFILES = $(filter-out $(FFILES) $(XFILES), $(FILES))

OTHERS = $(shell ls *.* | grep -v -E '\.(f|wxz)$$')

TYPED = $(patsubst %.fw, %.fwi, $(TFILES) $(XFILE)) \
	$(patsubst %.fw, %.fwe, $(FFILES))

PARSED = $(patsubst %.fw, %.fws, $(TFILES) $(XFILES))

LAST = $(shell ls -t $(FILES) | head -1)

last: $(filter $(patsubst %.fw, %, $(LAST)).%, $(TYPED))
	cat $<

all: $(TYPED)

parse: $(PARSED)

print: $(patsubst %.fs, %.fp, $(PARSE))

others:
	@ls $(OTHERS)

$(FOMEGA):
	make -C $(ROOT) all

%.fwi: %.fw $(FOMEGA)
	$(FOMEGA) $<  > $@ || (rm $@ && false)

%.fwe: %.fw $(FOMEGA)
	$(FOMEGA) --fail $<  2> $@ || (rm $@ && false)

%.fws: %.fw  $(FOMEGA)
	$(FOMEGA) --reparse --reprint --no-typing $< > $@ || \
	rm -f $@ && \
	$(FOMEGA) $< --reprint --no-typing > $*.s.fw && \
	make $*s.fwi

%.out: %.fwi
	@echo & echo "### $@ ###"
	@cat $<

clean:
	rm -f *.fw[ies]
